package(default_visibility = ["//visibility:public"])

load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "streamingcontainer",
    srcs = ["streamingcontainer.cc","streamingcontainer.h"],
    hdrs = ["streamingcontainer.h"],
    deps = ["@exaudfclient_base//exaudflib:exaudflib-deps","@exaudfclient_base//exaudflib:header"]
)
