load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "json_schema",
    hdrs = ["include/exasol/udf/v2/json_schema.hpp"],
    includes = ["include"],
    deps = ["@v2_json_schema_validator//:json_schema_validator"],
)

cc_test(
    name = "json_schema_validation_test",
    srcs = ["json_schema_validation_test.cc"],
    data = ["//json_schema:all_schemas"],
    copts = ["-std=c++17"],
    deps = [":json_schema"],
)
