module(name="exaudfclient", version = "1.0")

bazel_dep(name = "exaudfclient_base", version = "1.0.0")
#For now, the Bazel Modul "exaudfclient_base" is stored in subdirectory "base".
#Later we might fetch it via Http or Git (after splitting up script-languages repository)
local_path_override(module_name="exaudfclient_base", path="base")

zmq_local_repository = use_repo_rule("@exaudfclient_base//:zmq_repository.bzl", "zmq_local_repository")
zmq_local_repository(name = "zmq")

protobuf_local_repository = use_repo_rule("@exaudfclient_base//:protobuf_repository.bzl", "protobuf_local_repository")
protobuf_local_repository(name = "protobuf")
