filegroup(
    name = "config",
    srcs = [".clang-tidy"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "wrapper",
    srcs = ["clang-tidy-wrapper.sh"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "apply-replacements-wrapper",
    srcs = ["clang-apply-replacements-wrapper.sh"],
    visibility = ["//visibility:public"],
)
