name: Check v2 JSON schemas

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@v9
        with:
          python-version: "3.10"
          poetry-version: "2.3.0"

      - name: Install Poetry dependencies
        run: poetry install --with dev

      - name: Validate v2 JSON schemas
        run: poetry run nox -s validate-json-schemas
