name: Check Bazel Tests

on:
  push:
    branches:
      - master
  pull_request:

env:
  USE_BAZEL_VERSION: 8.3.1
  BAZEL_PACKAGE_VERSION: 8.3.1
  JAVA_PREFIX: /usr/lib/jvm/java-17-openjdk-amd64
  PYTHON3_PREFIX: /usr
  PYTHON3_VERSION: python3
  PROTOBUF_LIBRARY_PREFIX: /usr/lib/x86_64-linux-gnu
  PROTOBUF_INCLUDE_PREFIX: /usr/include
  ZMQ_LIBRARY_PREFIX: /usr/lib/x86_64-linux-gnu
  ZMQ_INCLUDE_PREFIX: /usr/include
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Search for duplicated error codes
        run: bash find_duplicate_error_codes.sh

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl libprotobuf-dev libzmq3-dev openjdk-17-jdk protobuf-compiler python3-dev python3-numpy valgrind
      - name: Install bazel
        run: |
          BAZEL_PACKAGE_FILE="bazel_$BAZEL_PACKAGE_VERSION-linux-x86_64.deb"
          BAZEL_PACKAGE_URL="https://github.com/bazelbuild/bazel/releases/download/$BAZEL_PACKAGE_VERSION/$BAZEL_PACKAGE_FILE"
          curl -L --output /tmp/"$BAZEL_PACKAGE_FILE" "$BAZEL_PACKAGE_URL"
          sudo apt install -y "/tmp/$BAZEL_PACKAGE_FILE"
          rm "/tmp/$BAZEL_PACKAGE_FILE"
      - name: Build
        run: |
          bazel build --lockfile_mode=off --config no-tty -c dbg --config fast-binary --verbose_failures //:udf_runner_cpp_v1_gen //:udf_runner_cpp_v1_static_gen
        working-directory: ./udf-runner-cpp/v1

  tests:
    runs-on: ubuntu-24.04
    strategy:
     fail-fast: false
     matrix:
        include:
          - test: "//exaudflib/test:exaudflib-test"
            name: "exaudflib"
          - test: "//script_options_parser/ctpg/test:script-options-ctpg-parser-test"
            name: "script_options_parser_ctpg"
          - test: "//script_options_parser/legacy/test:script-options-legacy-parser-test"
            name: "script_options_parser_legacy"
          - test: "--run_under='valgrind --leak-check=yes' --config=valgrind //exaudflib/test:exaudflib-test"
            name: "exaudflib_with_valgrind"
          - test: "--run_under='valgrind --leak-check=yes' --config=valgrind //script_options_parser/ctpg/test:script-options-ctpg-parser-test"
            name: "script_options_parser_ctpg_with_valgrind"
          - test: "--run_under='valgrind --leak-check=yes' --config=valgrind //script_options_parser/legacy/test:script-options-legacy-parser-test"
            name: "script_options_parser_legacy_with_valgrind"
          - test: "--config=asan //exaudflib/test:exaudflib-test"
            name: "exaudflib_with_asan"
          - test: "--config=asan //script_options_parser/ctpg/test:script-options-ctpg-parser-test"
            name: "script_options_parser_ctpg_with_asan"
          - test: "--config=asan //script_options_parser/legacy/test:script-options-legacy-parser-test"
            name: "script_options_parser_legacy_with_asan"
    steps:
      - uses: actions/checkout@v6
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl libprotobuf-dev libzmq3-dev openjdk-17-jdk protobuf-compiler python3-dev python3-numpy valgrind
      - name: Install bazel
        run: | 
          BAZEL_PACKAGE_FILE="bazel_$BAZEL_PACKAGE_VERSION-linux-x86_64.deb"
          BAZEL_PACKAGE_URL="https://github.com/bazelbuild/bazel/releases/download/$BAZEL_PACKAGE_VERSION/$BAZEL_PACKAGE_FILE"
          curl -L --output /tmp/"$BAZEL_PACKAGE_FILE" "$BAZEL_PACKAGE_URL"
          sudo apt install -y "/tmp/$BAZEL_PACKAGE_FILE"
          rm "/tmp/$BAZEL_PACKAGE_FILE"
        env:
          BAZEL_PACKAGE_VERSION: "8.3.1"
      - name: Run tests
        run: |
          bazel test ${{ matrix.test }}
        working-directory: ./udf-runner-cpp/v1/base
        env:
          OPENSSL_LIBRARY_PREFIX: "/usr/lib/x86_64-linux-gnu"
          OPENSSL_INCLUDE_PREFIX: "/usr/include/openssl"

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: "${{ matrix.name }}"
          path: /home/runner/.cache/bazel/_bazel_runner/*/execroot/_main/bazel-out/k8-dbg/testlogs/**/test.log
